export const REQUEST_MOVIES_SUCCESS = 'REQUEST_MOVIES_SUCCESS';
export const REQUEST_MOVIE_VIDEOS_SUCCESS = 'REQUEST_MOVIE_VIDEOS_SUCCESS';
export const REQUEST_MOVIE_DETAILS_SUCCESS = 'REQUEST_MOVIE_DETAILS_SUCCESS';
export const SEARCH_FIELD = 'SEARCH_FIELD';